- name: Configure Admin password
  asa_config:
    lines:
      - "username admin password {{ global_pass }} privilege 15"

- name: Get Existing Users
  asa_command:
    commands:
      - "show run username"
  register: existing_users
  when: purge_users | bool

- name: Remove All Other Users
  asa_config:
    src: templates/asa_purge.j2
  when: purge_users | bool
